### PR TITLE
General Cleanup.

### PR DESCRIPTION
**Pull request by a-kulkarn**

### CODE REVIEW

**Comment by edgarcosta** [comment]
Why are you pushing to elliptic points?

**Comment by edgarcosta** [comment]
Here a bit more of cleanup:
- One should polredabs the absolute field

Comment out the following lines
```
 //zeta := K.1;
 //t := Trace(zeta);
 //u := Norm(zeta);
//UK, mUK := UnitGroup(ZKabs)
```

```
-    for i in [1..#orders] do
-        Oq := orders[i]; dff := conductors[i];
+    for i->Oq in orders do
+        dff := conductors[i];
```

**Comment by a-kulkarn** [comment]
Oh, it said I couldn't automerge onto master. Not totally sure why.

**Comment by edgarcosta** [comment]
maybe it has to do with me fixing tab vs spaces
you can try to merge master into your branch

**Pull request merged**
