### PR TITLE
Computing cusps, step 1

### PR DESCRIPTION
**Pull request by SamSchiavone**
More functions for embedding into RR^2 and Shintani. First step in computing cusps as in Dasgupta-Kakde: R^ss_MM.

### CODE REVIEW

**Comment by SamSchiavone** [comment]
No worries, I've made an issue regarding your concern and assigned our top man to the task!

I'll certainly make a test once I finish with the other parts of the bijection to make sure the code is producing correct output.

**Comment by edgarcosta** [comment]
What about `RssM` = `ModQuotientByTotallyPositive`, and `ss=numerator`, `M=denominator`?

**Comment by SamSchiavone** [comment]
I still find your proposal pretty opaque. It's really the set of generators of the quotient module `s/(s*M)` modulo totally positive units. But `GeneratorsOfQuotientModuleModuloTotallyPositive` seems ludicrously long, even by Magma standards.

**Comment by edgarcosta** [comment]
`QuotientModuleModTotallyPositive`? anything that starts with `Quotient...` is better than `RssM`, which is extra cryptic, and hard to find.
We can fight this another day :P

**Comment by michaelmusty** [comment]
long descriptive name > cryptic name of any length (in my opinion)

**Comment by jvoight** [comment]
I was going to make a joke about trying to find a long cryptic name, but I fear github isn't the right place for comedy.

**Pull request merged**
